In [1]:
#import numpy library
import numpy as np

# Q1: Python Program to find sum of array

In [2]:
a = np.array([2,3,4,5,6,7])
a

array([2, 3, 4, 5, 6, 7])

In [3]:
a.sum()

27

# Q2: Python Program to find largest element in an array

In [4]:
max(a)

7

# Q3: Python Program for array rotation

In [5]:
print('Left Rotation')
for i in range(len(a)):
    for i in range(len(a) - 1):
        dummy = a[i+1]
        a[i + 1] = a[i]
        a[i] = dummy
    print(a)

Left Rotation
[3 4 5 6 7 2]
[4 5 6 7 2 3]
[5 6 7 2 3 4]
[6 7 2 3 4 5]
[7 2 3 4 5 6]
[2 3 4 5 6 7]


In [6]:
print('Right Rotation')
for i in range(len(a)):
    for i in range(len(a) - 1, 0,-1):
        dummy = a[i-1]
        a[i - 1] = a[i]
        a[i] = dummy
    print(a)

Right Rotation
[7 2 3 4 5 6]
[6 7 2 3 4 5]
[5 6 7 2 3 4]
[4 5 6 7 2 3]
[3 4 5 6 7 2]
[2 3 4 5 6 7]


# Q4: Python Program to Split the array and add the first part to the end

In [7]:
b = a[:3]
c = a[3:]
d = np.append(c, b)
d

array([5, 6, 7, 2, 3, 4])

# Q5: Python Program to check if given array is Monotonic

In [8]:
a = np.array([1,2,4,7,8,9])
b = np.array([5,3,6,2,8,4])

In [9]:
def monotonic(a):
    flag = 0
    if a[0] > a[1]:
        for i in range(len(a) -1):
            if a[i] > a[i+1]:
                pass
            else:
                flag = 1
            
    else:
        for i in range(len(a) -1):
            if a[i] < a[i+1]:
                pass
            else:
                flag = 1
            
    if flag == 0:
        print('Array is monotonic')
    else:
        print('Array is not monotonic')

In [10]:
monotonic(a)

Array is monotonic


In [11]:
monotonic(b)

Array is not monotonic
