In [1]:
#import numpy library
import numpy as np

In [2]:
A = np.array([[1,4,5], [3,4,3], [7,3,5]])
B = np.array([[2,0,2], [5,3,7], [6,1,1]])

# Q1: Python Program to Add Two Matrices

In [3]:
if A.shape == B.shape:
    print('Sum: \n{}'.format(A+B))

Sum: 
[[ 3  4  7]
 [ 8  7 10]
 [13  4  6]]


# Q2: Python Program to Multiply Two Matrices

In [4]:
if ((A.shape[1] == B.shape[0])):
    print('Multiplication: \n{}'.format(A*B))

Multiplication: 
[[ 2  0 10]
 [15 12 21]
 [42  3  5]]


# Q3: Python Program to Transpose a Matrix

In [5]:
for i in range(A.shape[0]):
    for j in range(i):
        A[i][j], A[j][i] = A[j][i], A[i][j] 
print('Transposed Matrix\n{}'.format(A))

Transposed Matrix
[[1 3 7]
 [4 4 3]
 [5 3 5]]


# Q4: Python Program to Sort Words in Alphabetic Order

In [7]:
l = ['efgh', 'abcd', 'eigh', 'sdvd', 'sdff', 'ddfe', 'afss', 'csff']

In [8]:
l.sort()
l

['abcd', 'afss', 'csff', 'ddfe', 'efgh', 'eigh', 'sdff', 'sdvd']

# Q5:Python Program to Remove Punctuation From a String

In [9]:
s = 'asdf.,fgbd-1233 4,.t d"vfd?dd:sgg'

In [10]:
s1 = ''
for i in s:
    if i.isalnum():
        s1 = s1+i
print(s1)

asdffgbd12334tdvfdddsgg
